# Generated by Django 2.2.7 on 2019-11-04 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Id do Produto')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='api.Client')),
            ],
            options={
                'unique_together': {('client', 'product_id')},
            },
        ),
        migrations.DeleteModel(
            name='WishlistClient',
        ),
    ]
