# Generated by Django 2.2.7 on 2019-11-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191104_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_id',
            field=models.CharField(max_length=40, verbose_name='Id do Produto'),
        ),
    ]
